parameters:
#    tha_store.example.class: Tha\StoreBundle\Example

services:
#    tha_store.example:
#        class: %tha_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
